from time import time

from app.types import DataStore
from app.utils import to_resp_bulk_string, to_resp_error

ENTRY_ID_NOT_ZERO_ERROR = b"ERR The ID specified in XADD must be greater than 0-0"
ENTRY_ID_EQUAL_OR_SMALLER_ERROR = (
    b"ERR The ID specified in XADD is equal or smaller than the target stream top item"
)


def handle(args: list[bytes], data_store: DataStore) -> bytes:
    stream_key = args[0]
    entry_id = args[1]
    key_value_pairs = args[2:]
    stream = data_store.get(stream_key, ([], None))[0]

    if entry_id == b"0-0":
        return to_resp_error(ENTRY_ID_NOT_ZERO_ERROR)

    if entry_id == b"*":
        entry_id = autogenerate_entry_id(stream)

    # Entry ID format: <millisecondsTime>-<sequenceNumber>, or '*' for auto-generated.
    new_milliseconds_time, new_sequence_number = (
        int(x) if x != b"*" else "*" for x in entry_id.split(b"-")
    )
    if new_sequence_number == "*":
        new_sequence_number = autogenerate_sequence_number(
            stream, int(new_milliseconds_time)
        )
        entry_id = f"{new_milliseconds_time}-{new_sequence_number}".encode()

    # Validate that the entry id:
    # - is in the format of <millisecondsTime>-<sequenceNumber>
    # - millisecondsTime is a valid integer
    # - sequenceNumber is a valid integer
    # - millisecondsTime >= last entry's millisecondsTime
    # - if equal millisecondsTime, sequenceNumber must be greater than last entry's
    for entry in stream:
        last_entry_id = entry[0]
        last_milliseconds_time, last_sequence_number = map(
            int, last_entry_id.split(b"-")
        )
        new_milliseconds_time, new_sequence_number = map(int, entry_id.split(b"-"))

        if new_milliseconds_time < last_milliseconds_time:
            return to_resp_error(ENTRY_ID_EQUAL_OR_SMALLER_ERROR)
        elif (
            new_milliseconds_time == last_milliseconds_time
            and new_sequence_number <= last_sequence_number
        ):
            return to_resp_error(ENTRY_ID_EQUAL_OR_SMALLER_ERROR)

    existing = data_store.get(stream_key)
    stream = existing[0] if existing is not None else []
    stream.append((entry_id, key_value_pairs))
    data_store[stream_key] = (stream, None)

    return to_resp_bulk_string(entry_id)


def autogenerate_sequence_number(
    stream: list[tuple[bytes, list[bytes]]], milliseconds_time: int
) -> int:
    """
    Autogenerates a sequence number based on existing stream entries.
    - Empty stream for given time part: starts at 0.
    - Same time part exists: last sequence number + 1.
    - Exception: time part is 0 defaults to sequence 1.
    """
    if not stream:
        return 1 if milliseconds_time == 0 else 0
    last_entry_id = stream[-1][0]
    last_milliseconds_time, last_sequence_number = map(int, last_entry_id.split(b"-"))
    if milliseconds_time == last_milliseconds_time:
        return last_sequence_number + 1
    return 0


def autogenerate_entry_id(stream: list[tuple[bytes, list[bytes]]]) -> bytes:
    """
    Autogenerates an entry ID for a new stream entry.
    The entry ID is in the format of <millisecondsTime>-<sequenceNumber>.
    - The millisecondsTime part is the current time in milliseconds.
    - The sequenceNumber part is autogenerated
    based on the existing entries in the stream with the same millisecondsTime part.
    """
    milliseconds_time = int(time() * 1000)
    sequence_number = autogenerate_sequence_number(stream, milliseconds_time)
    return f"{milliseconds_time}-{sequence_number}".encode()
